'use client'

import { today } from '@outlive/core'
import { useActivePlan } from '@/lib/store.ts'

/**
 * What a printed page has to say about itself.
 *
 * These documents get filed next to steel plates and reread years later by
 * somebody who was not in the room when they were made. A page with no plan
 * name and no date is a page nobody can tell is out of date.
 */
export function PrintHeader() {
  const plan = useActivePlan()
  if (!plan) return null

  return (
    <div className="print-only mb-4 border-b border-line pb-2 text-[9pt]">
      <p className="font-semibold">{plan.name}</p>
      <p>
        Printed {today()}. Plan last changed {plan.updatedAt}. Generated by outlive.diy, which
        models structure and is not advice. Nothing on this page is a secret.
      </p>
    </div>
  )
}
